# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [2]:
import numpy as np

In [3]:
# ejercicio 1
a = np.array([1, 2, 3, 4]) 
print(np.all(a != 0))

True


In [4]:
# ejercicio 2
a = np.array([0, 0, 2, 0]) 
print(np.any(a != 0))

True


In [5]:
# ejercicio 3
a = np.array([1, 2, np.nan, np.inf]) 
print(np.any(np.isnan(a)) or np.any(np.isinf(a)))

True


In [7]:
# ejercicio 4
a = np.array([1, 2, np.inf]) 
print(np.any(np.isinf(a)))

True


In [8]:
# ejercicio 5
a = np.array([1, np.nan, 3]) 
print(np.any(np.isnan(a)))

True


In [9]:
# ejercicio 6
a = np.array([1, 3, 5]) 
b = np.array([2, 3, 4]) 
print("Mayor:", a > b) 
print("Mayor o igual:", a >= b) 
print("Menor:", a < b) 
print("Menor o igual:", a <= b)

Mayor: [False False  True]
Mayor o igual: [False  True  True]
Menor: [ True False False]
Menor o igual: [ True  True False]


In [10]:
# ejercicio 7
a = np.array([1, 7, 13, 105]) 
print(a.nbytes, "bytes")

32 bytes


In [11]:
# ejercicio 8
print(np.zeros(10)) 
print(np.ones(10)) 
print(np.full(10, 5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [12]:
# ejercicio 9
print(np.arange(30, 71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [13]:
# ejercicio 10
print(np.arange(30, 71, 2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [14]:
# ejercicio 11
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# ejercicio 12
print(np.random.rand())

0.05316980255848669


In [16]:
# ejercicio 13
print(np.random.randn(15))

[ 2.67840043  0.08759719 -1.24842988 -2.67781456 -0.91703875  0.54583732
 -1.09040893  2.48913198  0.41208254 -1.11773597  0.64296726 -0.85382101
 -0.37820294 -1.50137733 -0.70256507]


In [17]:
# ejercicio 14
a = np.arange(15, 56) 
print(a[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [18]:
# ejercicio 15
print(np.linspace(5, 50, 10))

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [19]:
# ejercicio 16
a = np.arange(0, 21) 
a[(a >= 9) & (a <= 15)] *= -1 
print(a)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [20]:
# ejercicio 17
a = np.array([1, 2, 3]) 
print(a.tolist())

[1, 2, 3]


In [21]:
# ejercicio 18
l = [1, 2, 3] 
print(np.array(l))

[1 2 3]


In [22]:
# ejercicio 19
m = np.array([[1, 2], [3, 4]]) 
print(m % 2 == 0)

[[False  True]
 [False  True]]


In [23]:
# ejercicio 20
m = np.array([[1, 2, 3], [4, 5, 6]]) 
print("Filas:", m.shape[0]) 
print("Columnas:", m.shape[1])

Filas: 2
Columnas: 3
